# Generated by Django 2.2 on 2022-11-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbadata',
            name='logopath',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='球隊logo'),
        ),
    ]
